production:
  adapter: sqlite3
  database: db/production.db

development: &defaults
  adapter: sqlite3
  database: db/development.db

test:
  adapter: sqlite3
  database: db/test.db

rake:
  <<: *defaults
